contact_links:
  - name: "\u2615 The Turing Way events"
    url: https://hackmd.io/@turingway/demo-intro
    about: As core members, host or attend The Turing Way weekly and monthly events
  - name: "\U0001F5E3 Community engagement and general chat"
    url: https://join.slack.com/t/theturingway/shared_invite/zt-fn608gvb-h_ZSpoA29cCdUwR~TIqpBw
    about: Join The Turing Way Slack Workspace and chat with the community
